version: '2'
services:
  activiti_mysql:
    hostname: activiti_mysql
    container_name: activiti_mysql
    image: sameersbn/mysql:latest
    volumes:
      - ${COMPOSEROOT}/todo/mysqldata:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    environment:
      - DB_NAME=activiti_production
      - DB_USER=activiti
      - DB_PASS=pass1234
  
  activiti_server:
    hostname: activiti_server
    container_name: activiti_server
    image: dorissschoi/activiti:latest
    volumes:
      - /etc/localtime:/etc/localtime
    links:
      - activiti_mysql:mysql
    ports:
      - 8080  
    # for version 1 link env var
    environment:
      - DB_TYPE=mysql
      - DB_HOST=activiti_mysql
      - DB_PORT=3306
      # support for linked sameersbn/mysql image
      - DB_NAME=activiti_production
      - DB_USER=activiti
      - DB_PASS=pass1234               