version: '2'
services:
  activiti_mysql:
    hostname: activiti_mysql
    container_name: activiti_mysql
    image: mariadb  
    ports:
      - "3306"
    volumes:
      - ${COMPOSEROOT}/todo/newmysqldata:/var/lib/mysql
      - /etc/localtime:/etc/localtime       
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
  
  activiti_server:
    hostname: activiti_server
    container_name: activiti_server
    image: dorissschoi/activiti:latest
    volumes:
      - /etc/localtime:/etc/localtime
      - ./assets/config/tomcat/web.xml:/opt/tomcat/conf/web.xml
    links:
      - activiti_mysql:mysql
    ports:
      - 8080:8080  
    environment:
      - DB_HOST=
      - DB_PORT=
      - DB_NAME=
      - DB_USER=
      - DB_PASS=               